### ISSUE TITLE
test

### ISSUE THREAD

**Issue by dzzxjl** [Pines-Cheng/blog#14]
你好，以issue的方式提交blog很有趣，请问这是怎么实现的？非前端开发不是很了解，谢谢！

**Comment by Pines-Cheng** [comment]
[Mirror](https://github.com/LoeiFy/Mirror)

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/35893506-5328cdb4-0be9-11e8-9b57-33d42a6d6515.png)

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/35893530-74204006-0be9-11e8-830e-738f472a5ab4.png)

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/35893612-d6e464ba-0be9-11e8-8370-334b081ce71d.png)

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/35893672-207fbc50-0bea-11e8-8946-e94a2d6aea0a.png)

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/35893919-2f77d23c-0beb-11e8-8b27-f86f0a76e520.png)

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/36954526-adc8a7a2-205d-11e8-90d0-fdddcbcf1e57.png)

**Comment by Pines-Cheng** [comment]
![image](https://user-images.githubusercontent.com/9441951/36954638-519ab19a-205e-11e8-9fb9-41d8fab2b616.png)
